blank_issues_enabled: false
contact_links:
  - name: 提交主页到 PCL 仓库（Hex-Dragon）
    url: https://github.com/Hex-Dragon/PCL2/discussions/new?category=%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A1%B5&title=[新主页] 
    about: 提交 PCL 主页给龙猫审核，通过则加入 PCL2 预设主页
  - name: 提交主页到 PCL 非官方主页市场（HomePlaza-Of-PCL2）
    url: https://github.com/HomePlaza-Of-PCL2/Homepage-Market/issues/new?assignees=&labels=a%3A%E6%96%B0%E4%B8%BB%E9%A1%B5&projects=&template=4_new.yml&title=[新主页] 
    about: 提交 PCL 主页给 HomePlaza-Of-PCL2 组织审核，通过则加入 PCL 非官方主页市场
